# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-13 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0002_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='contact_details',
            name='message',
        ),
        migrations.AddField(
            model_name='contact_details',
            name='msg',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='uname',
            field=models.CharField(max_length=40),
        ),
    ]
