# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-13 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('accommodation_enquiry', models.CharField(max_length=40)),
                ('airconditioned_cabin', models.CharField(max_length=40)),
                ('date_of_arrival', models.CharField(max_length=40)),
                ('number_of_persons', models.CharField(max_length=40)),
                ('number_of_days', models.CharField(max_length=40)),
            ],
        ),
    ]
