# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk', '0005_bookrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('nofpeople', models.CharField(max_length=40)),
                ('items', models.CharField(max_length=40)),
            ],
        ),
    ]
